DESTDIR=~/.local/share/gnome-shell/extensions/

install:
	mkdir -p $(DESTDIR)/osk-replace@sulincix || true
	install extension.js $(DESTDIR)/osk-replace@sulincix/extension.js
	install metadata.json $(DESTDIR)/osk-replace@sulincix/metadata.json

